### ISSUE TITLE
Menu in 7.0 fails to find anything when scrolled

### ISSUE THREAD

**Issue by rnuernberg** [chameleon-system/chameleon-system#592] opened 2020-06-14 15:50 UTC
**Describe the bug**
When you expand a few of the primary menu items in the left side primary menu and then scroll the menu, then the menu search will no longer find any items.

**Affected version(s)**
7.0.x

**To Reproduce**
1. Expand a few of the primary menu items so that the menu becomes higher than your screen
2. scroll the menu a little bit
3. search for an item that exists in the menu search bar
4. nothing will be found

**Expected behavior**
The search should still work.

**Screenshots**
![2020-06-14-001](https://user-images.githubusercontent.com/1104497/84597923-5f2ef980-ae67-11ea-8f00-80d824e6ff46.png)

**Desktop (please complete the following information):**
 - Browser Chrome  83.0.4103.97

**Comment by UlrichKu** [comment] 2020-06-15 05:46
That's a duplicate of #570

**Closed by UlrichKu** 2020-06-15 05:46 UTC
