### ISSUE TITLE
Backend: optimization and bug fixes with js-plugin select2()

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#315] opened 2019-02-14 14:38 UTC
**Describe the bug**
There are some problems/questions/errors with the js-plugin select2():

1. For example in the menu item Table Settings @umulmrum searched for the term "cms" and confirmed, but the search was not always executed.
(I couldn't reproduce that, my search was always correctly, even for other terms...)
![selection_279](https://user-images.githubusercontent.com/26296728/52793593-59a48200-306e-11e9-973b-285583e5f6a1.jpg)

2. If you want to assign an instance to a spot, you can't search for the instance: 
![selection_276](https://user-images.githubusercontent.com/26296728/52792699-514b4780-306c-11e9-84fc-741440fc7924.jpg)

3. In the menu item "Update Directory": Select a bundle (e.g. AppBundle) and within the bundle search an update from the list. Without input many datasets with id 1 will be suggested. Can this be correct?
![selection_277](https://user-images.githubusercontent.com/26296728/52792814-8fe10200-306c-11e9-8bbb-a0ed47011174.jpg)
If you search for a specific update number, the record will be suggested twice:
![selection_278](https://user-images.githubusercontent.com/26296728/52792923-d20a4380-306c-11e9-979f-a52f1378d5aa.jpg)
That's probably because of the ajax search.

5. Finally, the question whether the first option of select2 should already be selected by default or whether this should only be done after the down arrow key has been pressed?
(But I haven't found an option to control this and normally I think it makes sense that the first option is already checked.)

**Affected version(s)**
V6.3

**Comment by pixeljunkie** [comment] 2019-02-15 15:01
1. can not confirm this bug anywhere
3. Nope. This is the right behavior... there ARE many records with the build_number "1". So everything is o.k. here.
If it should show the record ID instead the name field of the table needs to be reconfigured. There may be other tables with missing name field configuration.
4. fixed this

**Comment by pixeljunkie** [comment] 2019-02-15 15:42
(2.) disabled select2 autocomplete in all table list views where record editing is not possible.

**Comment by esono-anja** [comment] 2019-02-27 15:32
(3.) It looks as if the keyword list shows updates from all bundles (therefore the many "1"). Does this make sense? Please check with @umulmrum (we just discuseed it).
(3.) The reported bug "If you search for a specific update number, the record will be suggested twice" still occurs.
(4.) Search results are displayed after pressing the search button. Enter doesn't work. But isn't supposed to? I'm sure it worked before ( I tested it), but now it doesn't anymore.

**Comment by umulmrum** [comment] 2019-03-13 12:13
(3.) Yes, we get results for all migration counters. This explains both observations, so we can handle them the same. Could you have a glance at the database query @pixeljunkie ? By my interpretation we need to set sRestrictionField and sRestriction correctly.

Search behavior is still not optimal.
- I can confirm @esono-anja's observation that pressing Return doesn't do anything in the update index list. For "first-class" lists like the products it works though.
- The empty search result is still there.
- On a list where search works: When searching a second time without leaving the page, I'd expect the previous search term to be still in the search field, but it is empty.
- The message "Please enter 1 or more characters" isn't helpful as it is clear that a search field expects at least one character even without such message. Can we either remove the message or (if it makes sense of course) increase the character limit?

ping @pixeljunkie @ckleis

**Comment by pixeljunkie** [comment] 2019-03-15 09:52
>  It looks as if the keyword list shows updates from all bundles (therefore the many "1"). Does this make sense? Please check with @umulmrum (we just discuseed it).

Fixed. The restrictions where not passed to the autocomplete query here

> The empty search result is still there.

Fixed.

> The message "Please enter 1 or more characters" isn't helpful

Yes i know, but it is rendered by select2 without the possibility to disable this and we need the character limit for a reason. But i managed to hide the message using CSS.

> On a list where search works: When searching a second time without leaving the page, I'd expect the previous search term to be still in the search field, but it is empty.

This is annoying but not so easy to fix.
I will extract this as a new issue.

**Comment by pixeljunkie** [comment] 2019-03-15 10:16
> (4.) Search results are displayed after pressing the search button. Enter doesn't work. But isn't supposed to? I'm sure it worked before ( I tested it), but now it doesn't anymore.

This works for me. Could you check after my PR is merged? Be sure to clear the browser cache.

**Closed** 2019-03-18 14:57 UTC
Labels: Status: Test, Topic: UX, Type: Feature
