### ISSUE TITLE
Media manager: Remove old one

### ISSUE THREAD

**Issue by UlrichKu** [chameleon-system/chameleon-system#220] opened 2018-11-29 10:44 UTC
**Describe the solution you'd like**
The old implementation of the media manager should be removed.

Is replaced by MediaManagerBundle.

Also see https://github.com/chameleon-system/chameleon-system/issues/19 in this context.

**Comment by UlrichKu** [comment] 2018-11-29 10:45
Also see vendor/chameleon-system/chameleon-base/src/CoreBundle/private/library/classes/TCMSTableEditor/TCMSTableEditorMedia.class.php:415

**Comment by UlrichKu** [comment] 2018-11-29 10:47
Also fix the "width" field of cms_media table.

ie with this update:

`$data = TCMSLogChange::createMigrationQueryData('cms_field_conf', 'de')
  ->setFields([
      'translation' => 'Breite',
      'fieldclass' => '',
  ])
  ->setWhereEquals([
      'id' => TCMSLogChange::GetTableFieldId(TCMSLogChange::GetTableId('cms_media'), 'width'),
  ])
;
TCMSLogChange::update(__LINE__, $data);
 $data = TCMSLogChange::createMigrationQueryData('cms_field_conf', 'en')
    ->setFields([
        'translation' => 'Width',
    ])
    ->setWhereEquals([
        'id' => TCMSLogChange::GetTableFieldId(TCMSLogChange::GetTableId('cms_media'), 'width'),
    ])
;
TCMSLogChange::update(__LINE__, $data);`

**Comment by umulmrum** [comment] 2019-03-28 13:23
Duplicate of #25

**Closed** 2019-03-28 13:24 UTC
Labels: Type: Feature
