### ISSUE TITLE
Error on save with active changelog

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#331] opened 2019-02-25 12:34 UTC
**Describe the bug**
When saving a record for a table with active changelog, an internal server error is displayed (the record is saved nonetheless, but no changelog record).

**Affected version(s)**
Seen in master, might have been introduced in 6.2.6.

**To Reproduce**
1. Activate changelog for e.g. the product category table (shop_category).
2. Open any record for this table and save it.
3. See toaster message "Internal server error".

**Expected behavior**
The record and the changelog record get saved without error message.

**Technical details**
In `\TCMSTableEditorChangeLog::getOldFields()`, `$this->oTablePreChangeData` is null.

**Comment by UlrichKu** [comment] 2019-02-25 12:56
Probaly a duplicate of #279 - which is still open.

**Comment by esono-anja** [comment] 2019-03-27 10:01
The following error message occurs:
`Error! Ajax response: error`

**Comment by UlrichKu** [comment] 2019-03-28 07:07
Probably (only) the wrong thing deployed.

**Closed** 2019-04-01 07:32 UTC
Labels: Type: Bug
