### ISSUE TITLE
Backend: Table editor: lable and fields/text on the same height

### ISSUE THREAD

**Issue by ckleis** [chameleon-system/chameleon-system#316] opened 2019-02-14 14:45 UTC
**Describe the bug**
Sometimes the label und the text aren't on the same height. For example in products => variants:

![selection_280](https://user-images.githubusercontent.com/26296728/52794107-7beacf80-306f-11e9-8eed-10b78926ca0d.jpg)

**Comment by UlrichKu** [comment] 2019-11-05 09:04
Duplicate of #441

**Closed by UlrichKu** 2019-11-05 09:04 UTC
Labels: Type: Bug
